import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { v4 as uuidv4, validate as uuidValidate, version as uuidVersion } from 'uuid';

/**
 * UUID v4 format validation regex (same as used in API routes)
 */
const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Custom arbitrary that generates valid UUID v4 strings.
 * Uses the uuid library's v4 generator to ensure valid format.
 */
const uuidV4Arb: fc.Arbitrary<string> = fc.integer().map(() => uuidv4());

/**
 * Validates that a string is a valid UUID v4 format.
 * This is the same function used in the API routes.
 */
function isValidUuid(id: string): boolean {
  return UUID_V4_REGEX.test(id);
}

/**
 * Simulates owner ID matching logic from the API routes.
 * This is used to test authorization behavior.
 *
 * @param storedOwnerId - The owner ID stored in the database
 * @param requestOwnerId - The owner ID provided in the request
 * @returns true if the owner IDs match, false otherwise
 */
function checkOwnerAuthorization(
  storedOwnerId: string,
  requestOwnerId: unknown
): { authorized: boolean; error?: string; statusCode?: number } {
  // Check if ownerId is provided (Requirement 26.5)
  if (requestOwnerId === undefined || requestOwnerId === null || requestOwnerId === '') {
    return {
      authorized: false,
      error: 'Authentication required',
      statusCode: 401,
    };
  }

  // Validate ownerId is a string
  if (typeof requestOwnerId !== 'string') {
    return {
      authorized: false,
      error: 'Invalid owner ID format',
      statusCode: 400,
    };
  }

  // Validate ownerId is a valid UUID
  if (!isValidUuid(requestOwnerId)) {
    return {
      authorized: false,
      error: 'Invalid owner ID format',
      statusCode: 400,
    };
  }

  // Verify ownership - case-sensitive comparison (Requirements 26.3, 26.4)
  if (storedOwnerId !== requestOwnerId) {
    return {
      authorized: false,
      error: 'You do not have permission to perform this action',
      statusCode: 403,
    };
  }

  return { authorized: true };
}

/**
 * Simulates API error response formatting.
 * Tests that error responses follow the correct format from the design document.
 */
interface ApiErrorResponse {
  error: string;
  details?: Array<{ field: string; reason: string }>;
  id?: string;
}

function formatErrorResponse(
  statusCode: number,
  error: string,
  details?: Array<{ field: string; reason: string }>,
  resourceId?: string
): ApiErrorResponse {
  const response: ApiErrorResponse = { error };

  // 400 responses SHALL include a "details" field listing invalid fields
  if (statusCode === 400 && details) {
    response.details = details;
  }

  // 404 responses SHALL indicate the resource type and identifier not found
  if (statusCode === 404 && resourceId) {
    response.id = resourceId;
  }

  // 500 responses SHALL NOT expose internal system details
  // (error message is already generic for 500)

  return response;
}

/**
 * Feature: tone-sketch, Property 15: Owner Authorization
 *
 * *For any* update or delete request on a Melody with owner_id O:
 * - If request owner_id ≠ O, the request SHALL be rejected with 403 Forbidden
 * - If request lacks owner_id, the request SHALL be rejected with 403 Forbidden
 * - If request owner_id = O, the request SHALL be processed
 *
 * **Validates: Requirements 20.7, 21.7, 26.3, 26.4, 26.5**
 */
describe('Property 15: Owner Authorization', () => {
  describe('UUID v4 Validation', () => {
    it('should accept valid UUID v4 strings', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 1, max: 100 }),
          () => {
            const uuid = uuidv4();
            expect(isValidUuid(uuid)).toBe(true);
            expect(uuidValidate(uuid)).toBe(true);
            expect(uuidVersion(uuid)).toBe(4);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should accept UUID v4 strings generated by fc.uuid()', () => {
      fc.assert(
        fc.property(fc.uuid(), (uuid) => {
          // fast-check generates valid UUIDs
          expect(uuidValidate(uuid)).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it('should reject invalid UUID strings', () => {
      fc.assert(
        fc.property(
          fc.oneof(
            fc.constant(''),
            fc.constant('not-a-uuid'),
            fc.constant('12345678-1234-1234-1234-123456789012'), // Not v4 (version digit is 1)
            fc.constant('12345678-1234-5234-8234-123456789012'), // Not v4 (version digit is 5)
            fc.constant('g1234567-1234-4234-8234-123456789012'), // Invalid hex char 'g'
            fc.constant('12345678123441238234123456789012'), // Missing hyphens
            fc.constant('12345678-1234-4234-8234-12345678901'), // Too short
            fc.constant('12345678-1234-4234-8234-1234567890123'), // Too long
            fc.string({ minLength: 1, maxLength: 50 }).filter((s) => !UUID_V4_REGEX.test(s))
          ),
          (invalidUuid) => {
            expect(isValidUuid(invalidUuid)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject UUIDs with wrong version number', () => {
      fc.assert(
        fc.property(
          fc.constantFrom('1', '2', '3', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'),
          (versionChar) => {
            // Generate a UUID-like string with wrong version
            const invalidUuid = `12345678-1234-${versionChar}234-8234-123456789012`;
            expect(isValidUuid(invalidUuid)).toBe(false);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should validate UUID format structure (8-4-4-4-12 pattern)', () => {
      fc.assert(
        fc.property(fc.uuid(), (uuid) => {
          const parts = uuid.split('-');
          expect(parts.length).toBe(5);
          expect(parts[0].length).toBe(8);
          expect(parts[1].length).toBe(4);
          expect(parts[2].length).toBe(4);
          expect(parts[3].length).toBe(4);
          expect(parts[4].length).toBe(12);
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Owner ID Matching', () => {
    it('should authorize when owner IDs match exactly', () => {
      fc.assert(
        fc.property(uuidV4Arb, (ownerId) => {
          const result = checkOwnerAuthorization(ownerId, ownerId);
          expect(result.authorized).toBe(true);
          expect(result.error).toBeUndefined();
        }),
        { numRuns: 100 }
      );
    });

    it('should reject when owner IDs do not match', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          uuidV4Arb,
          (storedOwnerId, requestOwnerId) => {
            // Skip if UUIDs happen to be the same (extremely unlikely)
            if (storedOwnerId === requestOwnerId) return;

            const result = checkOwnerAuthorization(storedOwnerId, requestOwnerId);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(403);
            expect(result.error).toBe('You do not have permission to perform this action');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should perform case-sensitive owner ID comparison', () => {
      fc.assert(
        fc.property(uuidV4Arb, (ownerId) => {
          // Test uppercase version
          const uppercaseOwnerId = ownerId.toUpperCase();
          const lowercaseOwnerId = ownerId.toLowerCase();

          // If stored is lowercase and request is uppercase, should reject
          if (lowercaseOwnerId !== uppercaseOwnerId) {
            // Result of authorization check - we just verify UUIDs are valid
            checkOwnerAuthorization(lowercaseOwnerId, uppercaseOwnerId);
            // Note: The UUID regex is case-insensitive, but string comparison should be case-sensitive
            // So this depends on implementation - checking both are still valid UUIDs
            expect(isValidUuid(uppercaseOwnerId)).toBe(true);
            expect(isValidUuid(lowercaseOwnerId)).toBe(true);
          }
        }),
        { numRuns: 100 }
      );
    });

    it('should treat different case versions of same UUID as different for authorization', () => {
      // Use a specific UUID to test case sensitivity in string comparison
      const lowercaseUuid = 'a1b2c3d4-e5f6-4a7b-8c9d-e0f1a2b3c4d5';
      const uppercaseUuid = 'A1B2C3D4-E5F6-4A7B-8C9D-E0F1A2B3C4D5';
      const mixedCaseUuid = 'A1b2C3d4-E5f6-4A7b-8C9d-E0f1A2b3C4d5';

      // Both should be valid UUIDs (regex is case-insensitive)
      expect(isValidUuid(lowercaseUuid)).toBe(true);
      expect(isValidUuid(uppercaseUuid)).toBe(true);
      expect(isValidUuid(mixedCaseUuid)).toBe(true);

      // But string comparison for authorization should be case-sensitive
      // lowercase stored, uppercase provided - should NOT match
      const result1 = checkOwnerAuthorization(lowercaseUuid, uppercaseUuid);
      expect(result1.authorized).toBe(false);
      expect(result1.statusCode).toBe(403);

      // uppercase stored, lowercase provided - should NOT match
      const result2 = checkOwnerAuthorization(uppercaseUuid, lowercaseUuid);
      expect(result2.authorized).toBe(false);
      expect(result2.statusCode).toBe(403);

      // Same case should match
      const result3 = checkOwnerAuthorization(lowercaseUuid, lowercaseUuid);
      expect(result3.authorized).toBe(true);
    });
  });

  describe('Missing Owner ID Handling', () => {
    it('should reject when owner ID is missing (undefined)', () => {
      fc.assert(
        fc.property(uuidV4Arb, (storedOwnerId) => {
          const result = checkOwnerAuthorization(storedOwnerId, undefined);
          expect(result.authorized).toBe(false);
          expect(result.statusCode).toBe(401);
          expect(result.error).toBe('Authentication required');
        }),
        { numRuns: 100 }
      );
    });

    it('should reject when owner ID is null', () => {
      fc.assert(
        fc.property(uuidV4Arb, (storedOwnerId) => {
          const result = checkOwnerAuthorization(storedOwnerId, null);
          expect(result.authorized).toBe(false);
          expect(result.statusCode).toBe(401);
          expect(result.error).toBe('Authentication required');
        }),
        { numRuns: 100 }
      );
    });

    it('should reject when owner ID is empty string', () => {
      fc.assert(
        fc.property(uuidV4Arb, (storedOwnerId) => {
          const result = checkOwnerAuthorization(storedOwnerId, '');
          expect(result.authorized).toBe(false);
          expect(result.statusCode).toBe(401);
          expect(result.error).toBe('Authentication required');
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('Non-String Owner ID Handling', () => {
    it('should reject non-string owner ID values', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.oneof(
            fc.integer(),
            fc.double({ noNaN: true }),
            fc.boolean(),
            fc.array(fc.string()),
            fc.object(),
            fc.constant(Symbol('test'))
          ),
          (storedOwnerId, invalidOwnerId) => {
            const result = checkOwnerAuthorization(storedOwnerId, invalidOwnerId);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
            expect(result.error).toBe('Invalid owner ID format');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject number values even if they look like parts of a UUID', () => {
      fc.assert(
        fc.property(uuidV4Arb, (storedOwnerId) => {
          const result = checkOwnerAuthorization(storedOwnerId, 12345678);
          expect(result.authorized).toBe(false);
          expect(result.statusCode).toBe(400);
        }),
        { numRuns: 100 }
      );
    });

    it('should reject boolean values', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.boolean(),
          (storedOwnerId, boolValue) => {
            const result = checkOwnerAuthorization(storedOwnerId, boolValue);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject array values', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.array(uuidV4Arb, { minLength: 0, maxLength: 5 }),
          (storedOwnerId, arrayValue) => {
            const result = checkOwnerAuthorization(storedOwnerId, arrayValue);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject object values', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.record({ id: uuidV4Arb }),
          (storedOwnerId, objectValue) => {
            const result = checkOwnerAuthorization(storedOwnerId, objectValue);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('Invalid UUID String Rejection', () => {
    it('should reject string owner IDs that are not valid UUIDs', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.string({ minLength: 1, maxLength: 100 }).filter((s) => !UUID_V4_REGEX.test(s)),
          (storedOwnerId, invalidUuidString) => {
            const result = checkOwnerAuthorization(storedOwnerId, invalidUuidString);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
            expect(result.error).toBe('Invalid owner ID format');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('should reject UUID-like strings with invalid characters', () => {
      fc.assert(
        fc.property(
          uuidV4Arb,
          fc.constantFrom(
            '12345678-1234-4234-8234-12345678901g', // Invalid char 'g'
            'xxxxxxxx-xxxx-4xxx-8xxx-xxxxxxxxxxxx', // All x's (invalid)
            '12345678-1234-4234-8234-1234567890!@'  // Special chars
          ),
          (storedOwnerId, invalidUuid) => {
            const result = checkOwnerAuthorization(storedOwnerId, invalidUuid);
            expect(result.authorized).toBe(false);
            expect(result.statusCode).toBe(400);
          }
        ),
        { numRuns: 100 }
      );
    });
  });
});

/**
 * Feature: tone-sketch, Property 16: API Error Response Format
 *
 * *For any* API error response, the response body SHALL be a JSON object
 * containing an "error" field with a human-readable message. Additionally:
 * - 400 responses SHALL include a "details" field listing invalid fields
 * - 404 responses SHALL indicate the resource type and identifier not found
 * - 500 responses SHALL NOT expose internal system details
 *
 * **Validates: Requirements 28.1, 28.2, 28.3, 28.4**
 */
describe('Property 16: API Error Response Format', () => {
  describe('Error Response Structure', () => {
    it('all error responses should contain an "error" field with a string message', () => {
      fc.assert(
        fc.property(
          fc.constantFrom(400, 401, 403, 404, 500),
          fc.string({ minLength: 1, maxLength: 200 }),
          (statusCode, errorMessage) => {
            const response = formatErrorResponse(statusCode, errorMessage);
            expect(response).toHaveProperty('error');
            expect(typeof response.error).toBe('string');
            expect(response.error.length).toBeGreaterThan(0);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('error messages should be human-readable (non-empty strings)', () => {
      fc.assert(
        fc.property(
          fc.constantFrom(400, 401, 403, 404, 500),
          fc.string({ minLength: 5, maxLength: 200 }),
          (statusCode, errorMessage) => {
            const response = formatErrorResponse(statusCode, errorMessage);
            expect(response.error).toBe(errorMessage);
            expect(response.error.trim().length).toBeGreaterThan(0);
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('400 Bad Request Response Format', () => {
    it('400 responses should include a "details" field when validation errors exist', () => {
      fc.assert(
        fc.property(
          fc.array(
            fc.record({
              field: fc.string({ minLength: 1, maxLength: 50 }),
              reason: fc.string({ minLength: 1, maxLength: 200 }),
            }),
            { minLength: 1, maxLength: 10 }
          ),
          (details) => {
            const response = formatErrorResponse(400, 'Validation failed', details);
            expect(response).toHaveProperty('details');
            expect(Array.isArray(response.details)).toBe(true);
            expect(response.details!.length).toBe(details.length);
          }
        ),
        { numRuns: 100 }
      );
    });

    it('400 response details should list each invalid field with reason', () => {
      fc.assert(
        fc.property(
          fc.array(
            fc.record({
              field: fc.constantFrom('title', 'notes', 'tempo', 'synth', 'ownerId', 'id'),
              reason: fc.string({ minLength: 10, maxLength: 100 }),
            }),
            { minLength: 1, maxLength: 5 }
          ),
          (details) => {
            const response = formatErrorResponse(400, 'Validation failed', details);

            response.details!.forEach((detail, index) => {
              expect(detail).toHaveProperty('field');
              expect(detail).toHaveProperty('reason');
              expect(typeof detail.field).toBe('string');
              expect(typeof detail.reason).toBe('string');
              expect(detail.field).toBe(details[index].field);
              expect(detail.reason).toBe(details[index].reason);
            });
          }
        ),
        { numRuns: 100 }
      );
    });

    it('400 responses without details should not include "details" field', () => {
      const response = formatErrorResponse(400, 'Bad request');
      // When no details provided, the field is omitted
      expect(response.details).toBeUndefined();
    });
  });

  describe('404 Not Found Response Format', () => {
    it('404 responses should indicate the resource identifier', () => {
      fc.assert(
        fc.property(uuidV4Arb, (resourceId) => {
          const response = formatErrorResponse(404, 'Melody not found', undefined, resourceId);
          expect(response).toHaveProperty('id');
          expect(response.id).toBe(resourceId);
        }),
        { numRuns: 100 }
      );
    });

    it('404 responses should include error message about resource not found', () => {
      fc.assert(
        fc.property(uuidV4Arb, (resourceId) => {
          const response = formatErrorResponse(404, 'Melody not found', undefined, resourceId);
          expect(response.error).toBe('Melody not found');
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('500 Internal Error Response Format', () => {
    it('500 responses should not expose internal system details', () => {
      fc.assert(
        fc.property(
          fc.string({ minLength: 1, maxLength: 100 }),
          () => {
            // For 500 errors, we use a generic message
            const genericError = 'An unexpected error occurred';
            const response = formatErrorResponse(500, genericError);

            expect(response.error).toBe(genericError);
            // Should not contain stack traces, file paths, or sensitive info
            expect(response.error).not.toContain('Error:');
            expect(response.error).not.toContain('at ');
            expect(response.error).not.toContain('.ts');
            expect(response.error).not.toContain('.js');
            expect(response.error).not.toContain('node_modules');
            // Should not expose database details
            expect(response.error.toLowerCase()).not.toContain('postgres');
            expect(response.error.toLowerCase()).not.toContain('database');
            expect(response.error.toLowerCase()).not.toContain('sql');
          }
        ),
        { numRuns: 100 }
      );
    });

    it('500 responses should not include details field', () => {
      const response = formatErrorResponse(500, 'An unexpected error occurred');
      expect(response.details).toBeUndefined();
      expect(response.id).toBeUndefined();
    });
  });

  describe('403 Forbidden Response Format', () => {
    it('403 responses should indicate action is not permitted', () => {
      fc.assert(
        fc.property(uuidV4Arb, () => {
          const response = formatErrorResponse(403, 'You do not have permission to perform this action');
          expect(response.error).toBe('You do not have permission to perform this action');
          expect(response.details).toBeUndefined();
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('401 Unauthorized Response Format', () => {
    it('401 responses should indicate authentication is required', () => {
      fc.assert(
        fc.property(uuidV4Arb, () => {
          const response = formatErrorResponse(401, 'Authentication required');
          expect(response.error).toBe('Authentication required');
          expect(response.details).toBeUndefined();
        }),
        { numRuns: 100 }
      );
    });
  });
});
